# Generated by Django 5.0.6 on 2024-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], null=True),
        ),
    ]
